nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:3000']
        allow_headers: ['X-API-KEY', 'Origin', 'X-Requested-With', 'Accept', 'Access-Control-Request-Method','Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        expose_headers: ['lin']
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~

    paths:
        '^/api/':
            origin_regex: true
            allow_origin: ['http://localhost:3000']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['X-API-KEY', 'Origin', 'X-Requested-With', 'Accept', 'Access-Control-Request-Method','Content-Type', 'Authorization']
            allow_credentials: true
            expose_headers: ['Link']
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['http://localhost:3000']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['X-API-KEY', 'Origin', 'X-Requested-With', 'Accept', 'Access-Control-Request-Method','Content-Type', 'Authorization']
            allow_credentials: true
            max_age: 3600
            hosts: ['^api\.']